# ===============================
# Application
# ===============================
spring.application.name=riskanalyzer

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/riskanalyzer
spring.datasource.username=postgres
spring.datasource.password=Pavithra@Neelesh
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===============================
# External APIs
# ===============================
etherscan.api.key=7SGHQ1YCUFIK6Q9QDM5R3UAU3MJ51XG4PI

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE